version: '2.4'

services:      
  web:
    build: ./app
    container_name: web
    restart: always
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - .env.dev
    depends_on:
      - database
    volumes:
      - ./static:/app/app/static
      
  database:
    image: postgres:13.0
    restart: always
    container_name: database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev
    ports:
      - 5432:5432
      
  nginx:
    build: ./nginx
    restart: always
    container_name: nginx
    volumes:
      - ./static:/static
    ports:
      - 80:80
    depends_on:
      - web
        
  grafana:
    image: grafana/grafana
    restart: always
    expose:
      - 3000
    ports:
      - 3000:3000
    env_file:
      - .env.dev
    
  clickhouse:
    image: yandex/clickhouse-server
    restart: always
    expose:
      - 8123
      - 9000
    ports:
      - 9000:9000
      - 8123:8123
    volumes:
      - ./clickhouse-config.xml:/etc/clickhouse-server/config.xml

volumes:
  postgres_data:

